=== nes-open-db/nes-open-db/_data/roms_index.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "array",
  "title": "ROM list",
  "default": null,
  "items": {
    "$id": "#/items",
    "type": "object",
    "title": "ROM",
    "default": null,
    "if": {
      "properties": {
        "platform": { "enum": ["nes"] }
      }
    },
    "then": { "required": ["runsOnJSNES"] },
    "required": [
      "added",
      "platform",
      "minPlayers",
      "maxPlayers",
      "key",
      "title",
      "detailsLink",
      "romLink",
      "screenshots"
    ],
    "properties": {
      "added": {
        "$id": "#/items/properties/added",
        "type": "string",
        "title": "Added",
        "description": "When the ROM was added to the database",
        "examples": [
          "2019-01-29"
        ],
        "pattern": "^[\\d-]+$"
      },
      "released": {
        "$id": "#/items/properties/released",
        "type": "string",
        "title": "Released",
        "description": "Original release date for the ROM",
        "examples": [
          "2018-02-24"
        ],
        "pattern": "^[\\d-]+$"
      },
      "platform": {
        "$id": "#/items/properties/platform",
        "type": "string",
        "enum": [
          "nes", "snes", "gba", "c64", "colecovision", "atari2600", "md", "sms", "zxspectrum"
        ],
        "title": "Platform",
        "description": "The platform that the ROM runs on",
        "examples": [
          "nes"
        ]
      },
      "minPlayers": {
        "$id": "#/items/properties/minPlayers",
        "type": "integer",
        "title": "Minimum players",
        "default": 1,
        "examples": [
          1
        ]
      },
      "maxPlayers": {
        "$id": "#/items/properties/maxPlayers",
        "type": "integer",
        "title": "Maximum players",
        "default": 1,
        "examples": [
          1
        ]
      },
      "key": {
        "$id": "#/items/properties/key",
        "type": "string",
        "title": "Reference key",
        "default": "",
        "examples": [
          "megamountain"
        ],
        "pattern": "^(.*)$"
      },
      "title": {
        "$id": "#/items/properties/title",
        "type": "string",
        "title": "ROM title",
        "default": "",
        "examples": [
          "Mega Mountain: NES Edition"
        ],
        "pattern": "^(.*)$"
      },
      "authors": {
        "$id": "#/items/properties/authors",
        "type": "array",
        "title": "The Authors Schema",
        "default": null,
        "items": {
          "$id": "#/items/properties/authors/items",
          "type": "object",
          "title": "Author",
          "default": null,
          "required": [
            "role",
            "key"
          ],
          "properties": {
            "role": {
              "$id": "#/items/properties/authors/items/properties/role",
              "type": "string",
              "enum": [
                "main",
                "developer",
                "graphics",
                "music"
              ],
              "title": "Role",
              "default": "main",
              "examples": [
                "main"
              ],
              "pattern": "^(.*)$"
            },
            "key": {
              "$id": "#/items/properties/authors/items/properties/key",
              "type": "string",
              "title": "Author reference key",
              "default": "",
              "examples": [
                "adrianmakesgames"
              ],
              "pattern": "^(.*)$"
            }
          }
        }
      },
      "detailsLink": {
        "$id": "#/items/properties/detailsLink",
        "type": "string",
        "title": "Details link",
        "description": "URL to details page",
        "default": "",
        "examples": [
          "/roms/megamountain/"
        ],
        "pattern": "^(.*)$"
      },
      "romLink": {
        "$id": "#/items/properties/romLink",
        "type": "string",
        "title": "ROM link",
        "description": "URL to ROM data",
        "examples": [
          "/roms/megamountain/megamountain.nes"
        ],
        "pattern": "^(.*)$"
      },
      "screenshots": {
        "$id": "#/items/properties/screenshots",
        "type": "array",
        "title": "Screenshots",
        "default": null,
        "items": {
          "$id": "#/items/properties/screenshots/items",
          "type": "string",
          "title": "Screenshot",
          "examples": [
            "/roms/megamountain/screenshots/1.gif",
            "/roms/megamountain/screenshots/2.gif"
          ],
          "pattern": "^(.*)$"
        }
      },
      "license": {
        "$id": "#/items/properties/license",
        "type": "string",
        "title": "License",
        "description": "License which the ROM is under",
        "default": "",
        "examples": [
          "CC-BY-SA 4.0"
        ],
        "pattern": "^(.*)$"
      },
      "licenseLink": {
        "$id": "#/items/properties/licenseLink",
        "type": "string",
        "title": "License link",
        "description": "Link to the full description of the license",
        "default": "",
        "examples": [
          "https://creativecommons.org/licenses/by-sa/4.0/"
        ],
        "pattern": "^(.*)$"
      },
      "tags": {
        "$id": "#/items/properties/tags",
        "type": "array",
        "title": "Tags",
        "description": "Tags that describe ROM e.g. genre",
        "default": null,
        "items": {
          "$id": "#/items/properties/tags/items",
          "type": "string",
          "title": "Tag",
          "default": "",
          "examples": [
            "platformer"
          ]
        }
      },
      "sourceCodeLink": {
        "$id": "#/items/properties/sourceCodeLink",
        "type": "string",
        "title": "Source code link",
        "description": "Link to the source code of the ROM",
        "examples": [
          "/roms/megamountain/megamountain_source.zip"
        ]
      },
      "runsOnJSNES": {
        "$id": "#/items/properties/runsOnJSNES",
        "type": "boolean",
        "title": "Runs on JSNES",
        "description": "Whether the ROM can be played on the JSNES emulator. Must be tested",
        "default": false
      }
    }
  }
}

=== nes-open-db/nes-open-db/_data/roms/nes.json
[
  {
    "added": "2019-01-29",
    "released": "2018-02-24",
    "platform": "nes",
    "minPlayers": 1,
    "maxPlayers": 1,
    "key": "megamountain",
    "title": "Mega Mountain: NES Edition",
    "authors": [
      {
        "role": "main",
        "key": "adrianmakesgames"
      }
    ],
    "detailsLink": "/roms/nes/megamountain/",
    "romLink": "/roms/nes/megamountain/megamountain.nes",
    "screenshots": [
      "/roms/nes/megamountain/screenshots/1.gif",
      "/roms/nes/megamountain/screenshots/2.gif"
    ],
    "license": "CC-BY-SA 4.0",
    "licenseLink": "https://creativecommons.org/licenses/by-sa/4.0/",
    "tags": [
      "platformer"
    ],
    "sourceCodeLink": "/roms/nes/megamountain/megamountain_source.zip",
    "runsOnJSNES": true
  },
  {
    "added": "2019-01-29",
    "released": "2019-01-28",
    "platform": "nes",
    "minPlayers": 1,
    "maxPlayers": 1,
    "key": "melojellos2",
    "title": "Melo-Jellos 2",
    "authors": [
      {
        "role": "main",
        "key": "adrianmakesgames"
      }
    ],
    "detailsLink": "/roms/nes/melojellos2/",
    "romLink": "/roms/nes/melojellos2/melojellos2.nes",
    "screenshots": [
      "/roms/nes/melojellos2/screenshots/1.png",
      "/roms/nes/melojellos2/screenshots/2.png",
      "/roms/nes/melojellos2/screenshots/3.png"
    ],
    "license": "CC-BY-SA 4.0",
    "licenseLink": "https://creativecommons.org/licenses/by-sa/4.0/",
    "tags": [
      "puzzle"
    ],
    "sourceCodeLink": "/roms/nes/melojellos2/melojellos2_source.zip",
    "runsOnJSNES": true
  },
  {
    "added": "2019-01-30",
    "released": "2018-01-31",
    "platform": "nes",
    "minPlayers": 1,
    "maxPlayers": 1,
    "key": "robo-ninja-climb",
    "title": "Robo-Ninja Climb",
    "authors": [
      {
        "role": "main",
        "key": "nathantolbert"
      }
    ],
    "detailsLink": "/roms/nes/robo-ninja-climb/",
    "romLink": "/roms/nes/robo-ninja-climb/robo-ninja-climb.nes",
    "screenshots": [
      "/roms/nes/robo-ninja-climb/screenshots/1.png",
      "/roms/nes/robo-ninja-climb/screenshots/2.png"
    ],
    "license": "CC BY-NC-ND 3.0",
    "licenseLink": "https://creativecommons.org/licenses/by-nc-nd/3.0/",
    "tags": [
      "action"
    ],
    "runsOnJSNES": true
  },
  {
    "added": "2019-01-30",
    "released": "2019-01-04",
    "platform": "nes",
    "minPlayers": 1,
    "maxPlayers": 4,
    "key": "super-homebrew-war",
    "title": "Super Homebrew War",
    "authors": [
      {
        "role": "main",
        "key": "nathantolbert"
      }
    ],
    "detailsLink": "/roms/nes/super-homebrew-war/",
    "romLink": "/roms/nes/super-homebrew-war/super-homebrew-war.nes",
    "screenshots": [
      "/roms/nes/super-homebrew-war/screenshots/1.png",
      "/roms/nes/super-homebrew-war/screenshots/2.png"
    ],
    "license": "CC BY-NC-ND 3.0",
    "licenseLink": "https://creativecommons.org/licenses/by-nc-nd/3.0/",
    "tags": [
      "fighting"
    ],
    "runsOnJSNES": true
  },
  {
    "added": "2019-02-01",
    "released": "2016",
    "platform": "nes",
    "minPlayers": 1,
    "maxPlayers": 4,
    "key": "spacey-mcracey",
    "title": "Spacey McRacey",
    "authors": [
      {
        "role": "main",
        "key": "nathantolbert"
      }
    ],
    "detailsLink": "/roms/nes/spacey-mcracey/",
    "romLink": "/roms/nes/spacey-mcracey/spacey-mcracey.nes",
    "screenshots": [
      "/roms/nes/spacey-mcracey/screenshots/1.png",
      "/roms/nes/spacey-mcracey/screenshots/2.png"
    ],
    "license": "CC BY-NC-ND 3.0",
    "licenseLink": "https://creativecommons.org/licenses/by-nc-nd/3.0/",
    "tags": [
      "party",
      "racing"
    ],
    "runsOnJSNES": true
  },
  {
    "added": "2019-02-02",
    "released": "2019-01-31",
    "platform": "nes",
    "minPlayers": 1,
    "maxPlayers": 4,
    "key": "nesert-golfing",
    "title": "NESert Golfing",
    "authors": [
      {
        "role": "main",
        "key": "bradsmith"
      }
    ],
    "detailsLink": "/roms/nes/nesert-golfing/",
    "romLink": "/roms/nes/nesert-golfing/nesert-golfing.nes",
    "screenshots": [
      "/roms/nes/nesert-golfing/screenshots/1.png",
      "/roms/nes/nesert-golfing/screenshots/2.png",
      "/roms/nes/nesert-golfing/screenshots/3.png"
    ],
    "license": "CC BY 4.0",
    "licenseLink": "https://creativecommons.org/licenses/by/4.0/",
    "tags": [
      "sports",
      "golf",
      "minimalistic"
    ],
    "runsOnJSNES": true
  },
  {
    "added": "2019-02-03",
    "released": "2018-09-01",
    "platform": "nes",
    "minPlayers": 1,
    "maxPlayers": 1,
    "key": "kubo",
    "title": "KUBO",
    "authors": [
      {
        "role": "main",
        "key": "seiji"
      },
      {
        "role": "main",
        "key": "dalecoop"
      }
    ],
    "detailsLink": "/roms/nes/kubo/",
    "romLink": "/roms/nes/kubo/kubo.nes",
    "screenshots": [
      "/roms/nes/kubo/screenshots/1.png",
      "/roms/nes/kubo/screenshots/2.png",
      "/roms/nes/kubo/screenshots/3.png"
    ],
    "license": "CC BY 4.0",
    "licenseLink": "https://creativecommons.org/licenses/by/4.0/",
    "tags": [
      "adventure",
      "NESMaker"
    ],
    "runsOnJSNES": false,
    "description": "KUBO, the story of a cowboy turtle on his quest for a mysterious crystal hidden in a dangerous world, full of monsters.\n\nIt's a 1 level game. You beat the monsters, you find the crystal, you win.\n\nCreated by a 6yo boy (Seiji), this game is a son & father's summer 8bit project (using NESMaker)."
  },
  {
    "added": "2019-02-07",
    "key": "31in1realgame-multicart",
    "platform": "nes",
    "title": "31 In 1 Real Game!",
    "released": "2016-01-01",
    "description": "We would like to share with you all our own Multicart. 31 real games! Lots of laughs! Facepalms! Controllers flying accross the room! Mysterious secrets! Fake names! Repeat games with different sprites! Everything in 3 megabits full of love and kisses.",
    "screenshots": [
      "/roms/nes/31in1realgame-multicart/screenshots/31in1realgame-multicart.png"
    ],
    "detailsLink": "/roms/nes/31in1realgame-multicart/",
    "romLink": "/roms/nes/31in1realgame-multicart/31in1realgame-multicart.nes",
    "authorString": "Mojon Twins",
    "minPlayers": 1,
    "maxPlayers": 1,
    "license": "GPLv3",
    "licenseLink": "https://www.gnu.org/licenses/gpl-3.0.en.html",
    "tags": [
      "multicart"
    ],
    "runsOnJSNES": false
  },
  {
    "added": "2019-02-07",
    "key": "3in12ppak",
    "platform": "nes",
    "title": "3-In-1 2P Pak",
    "released": "2016-08-01",
    "description": "Do you like tic-tac-toe? Do you like the pegboard game? Do you like !CLIK!? What if they were also two-player competitive on the NES? Well then this game's for you! Compete against a friend, or play witchoself (get those tissues, though)! There are 3 different 2-player games, along with a bonus 2-player game that you can unlock after beating all the games as 1-player. If you look around, you might also find ANOTHER 2-player only game that is hidden within!",
    "screenshots": [
      "/roms/nes/3in12ppak/screenshots/3in12ppak.png"
    ],
    "detailsLink": "/roms/nes/3in12ppak/",
    "romLink": "/roms/nes/3in12ppak/3in12ppak.nes",
    "authorString": "SlyDog Studios",
    "minPlayers": 2,
    "maxPlayers": 2,
    "tags": [
      "multicart"
    ],
    "runsOnJSNES": true
  },
  {
    "added": "2019-02-07",
    "key": "ambushed",
    "platform": "nes",
    "title": "Ambushed",
    "released": "2015-06-15",
    "description": "You're walking down the street and suddenly, from a couple of attached buildings that are across the street, you are ambushed by multiple gunmen...",
    "screenshots": [
      "/roms/nes/ambushed/screenshots/ambushed.png"
    ],
    "detailsLink": "/roms/nes/ambushed/",
    "romLink": "/roms/nes/ambushed/ambushed.nes",
    "authorString": "SlyDog Studios",
    "minPlayers": 1,
    "maxPlayers": 1,
    "runsOnJSNES": true,
    "tags": [
      "first person shooter"
    ]
  },
  {
    "added": "2019-02-07",
    "key": "assimilate",
    "platform": "nes",
    "title": "Assimilate",
    "released": "2012-08-06",
    "description": "In Assimilate you control an alien space ship named Ossan and your main task is to kidnap humans, while the forces of the earth try to stop you from that.",
    "screenshots": [
      "/roms/nes/assimilate/screenshots/assimilate.png"
    ],
    "detailsLink": "/roms/nes/assimilate/",
    "romLink": "/roms/nes/assimilate/assimilate.nes",
    "authorString": "Nessylum Games",
    "minPlayers": 1,
    "maxPlayers": 1,
    "tags": ["action", "sci-fi"],
    "runsOnJSNES": false
  },
  {
    "added": "2019-02-07",
    "key": "babelblox",
    "platform": "nes",
    "title": "Babel Blox",
    "released": "2018-07-10",
    "description": "In the land of Shinar, the people are building a tower to elevate themselves to the level of God. Take on the role of God, and scramble the language of the people and scatter them on the earth! Use twitch-style skills to recognize different languages and stop blocks from being added to the construction of the tower. Choose from a variety of languages to use, and get the people separated!",
    "screenshots": [
      "/roms/nes/babelblox/screenshots/babelblox.png"
    ],
    "detailsLink": "/roms/nes/babelblox/",
    "romLink": "/roms/nes/babelblox/babelblox.nes",
    "authorString": "SlyDog Studios",
    "minPlayers": 1,
    "maxPlayers": 1,
    "runsOnJSNES": false
  },
  {
    "added": "2019-02-07",
    "key": "blaster",
    "platform": "nes",
    "title": "Big City Sliding Blaster",
    "released": "2014-06-02",
    "description": "Sliding Blaster by NovaSquirrel, a homebrew NES game released in 2014.",
    "screenshots": [
      "/roms/nes/blaster/screenshots/blaster.png"
    ],
    "detailsLink": "/roms/nes/blaster/",
    "romLink": "/roms/nes/blaster/blaster.nes",
    "authorString": "HLC! Project",
    "minPlayers": 1,
    "maxPlayers": 1,
